//! Tensor FFI — exposes candle tensor operations via `#[furst_export] impl`.
//!
//! Uses the opaque handle pattern: `ForgeTensor` and `ForgeVar` are heap-allocated,
//! F# gets typed classes with IDisposable + Finalize (auto-generated by furst-codegen).

use candle_core::{DType, Device, Tensor, Var};
use furst_macro::furst_export;

use crate::error::set_last_error;

/// Opaque handle wrapping a candle `Tensor`.
pub struct ForgeTensor {
    pub(crate) inner: Tensor,
}

/// Opaque handle wrapping a candle `Var` (trainable parameter).
pub struct ForgeVar {
    pub(crate) inner: Var,
}

// ─── Helpers ─────────────────────────────────────────────────────────────

fn device_from_i32(d: i32) -> Result<Device, candle_core::Error> {
    match d {
        0 => Ok(Device::Cpu),
        n => Device::new_cuda(n as usize - 1),
    }
}

fn shape_from_raw(shape_ptr: *const i64, shape_len: usize) -> Vec<usize> {
    let slice = unsafe { std::slice::from_raw_parts(shape_ptr, shape_len) };
    slice.iter().map(|&d| d as usize).collect()
}

// ─── ForgeTensor ─────────────────────────────────────────────────────────

/// Generates: forge_tensor_zeros, forge_tensor_from_f32, forge_tensor_matmul, etc.
/// Auto-generates forge_tensor_free with IDisposable + Finalize in F#.
#[furst_export]
impl ForgeTensor {
    /// Create a tensor of zeros. `device`: 0=CPU, 1=CUDA:0, 2=CUDA:1, ...
    pub fn zeros(shape_ptr: *const i64, shape_len: usize, device: i32) -> Self {
        let shape = shape_from_raw(shape_ptr, shape_len);
        let dev = device_from_i32(device).expect("invalid device");
        let t = Tensor::zeros(shape.as_slice(), DType::F32, &dev).expect("zeros failed");
        ForgeTensor { inner: t }
    }

    /// Create a tensor from a float32 slice.
    pub fn from_f32(
        data: *const f32,
        data_len: usize,
        shape_ptr: *const i64,
        shape_len: usize,
        device: i32,
    ) -> Self {
        let slice = unsafe { std::slice::from_raw_parts(data, data_len) };
        let shape = shape_from_raw(shape_ptr, shape_len);
        let dev = device_from_i32(device).expect("invalid device");
        let t = Tensor::from_slice(slice, shape.as_slice(), &dev).expect("from_f32 failed");
        ForgeTensor { inner: t }
    }

    /// Matrix multiplication. Returns a new tensor.
    pub fn matmul(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.matmul(other).expect("matmul failed") }
    }

    /// Element-wise addition. Returns a new tensor.
    pub fn add(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.add(other).expect("add failed") }
    }

    /// Element-wise subtraction. Returns a new tensor.
    pub fn sub(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.sub(other).expect("sub failed") }
    }

    /// Element-wise multiplication. Returns a new tensor.
    pub fn mul(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.mul(other).expect("mul failed") }
    }

    /// Element-wise division. Returns a new tensor.
    pub fn div(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.div(other).expect("div failed") }
    }

    /// Negate all elements.
    pub fn neg(&self) -> Self {
        ForgeTensor { inner: self.inner.neg().expect("neg failed") }
    }

    /// Multiply all elements by a scalar.
    pub fn mul_scalar(&self, scalar: f64) -> Self {
        ForgeTensor { inner: (self.inner.clone() * scalar).expect("mul_scalar failed") }
    }

    /// Add a scalar to all elements.
    pub fn add_scalar(&self, scalar: f64) -> Self {
        ForgeTensor { inner: (self.inner.clone() + scalar).expect("add_scalar failed") }
    }

    // ── Activations & custom ops ────────────────────────────────────────

    /// Sigmoid activation: 1 / (1 + exp(-x)).
    pub fn sigmoid(&self) -> Self {
        let result = crate::ops::sigmoid::Sigmoid::forward(&self.inner).expect("sigmoid failed");
        ForgeTensor { inner: result }
    }

    /// SiLU activation (x * sigmoid(x)).
    pub fn silu(&self) -> Self {
        let result = crate::ops::silu::Silu::forward(&self.inner).expect("silu failed");
        ForgeTensor { inner: result }
    }

    /// Softplus activation: log(1 + exp(x)).
    pub fn softplus(&self) -> Self {
        let result = crate::ops::softplus::Softplus::forward(&self.inner).expect("softplus failed");
        ForgeTensor { inner: result }
    }

    /// RMS Norm: x * rsqrt(mean(x²) + eps) * gamma.
    /// `gamma` is the weight tensor [N], `eps` is the epsilon value.
    pub fn rms_norm(&self, gamma: *const ForgeTensor, eps: f64) -> Self {
        let gamma = unsafe { &(*gamma).inner };
        let result = crate::ops::rms_norm::RmsNorm::forward(&self.inner, gamma, eps)
            .expect("rms_norm failed");
        ForgeTensor { inner: result }
    }

    /// Softmax along a given dimension.
    pub fn softmax(&self, dim: i64) -> Self {
        let dim = if dim < 0 {
            (self.inner.rank() as i64 + dim) as usize
        } else {
            dim as usize
        };
        let result = candle_nn::ops::softmax(&self.inner, dim).expect("softmax failed");
        ForgeTensor { inner: result }
    }

    // ── Reduction ops ───────────────────────────────────────────────────

    /// Element-wise square: x².
    pub fn sqr(&self) -> Self {
        ForgeTensor { inner: self.inner.sqr().expect("sqr failed") }
    }

    /// Element-wise square root.
    pub fn sqrt(&self) -> Self {
        ForgeTensor { inner: self.inner.sqrt().expect("sqrt failed") }
    }

    /// Sum of all elements (scalar tensor).
    pub fn sum_all(&self) -> Self {
        ForgeTensor { inner: self.inner.sum_all().expect("sum_all failed") }
    }

    /// Mean of all elements (scalar tensor).
    pub fn mean_all(&self) -> Self {
        ForgeTensor { inner: self.inner.mean_all().expect("mean_all failed") }
    }

    /// Clamp all elements to [min, max].
    pub fn clamp(&self, min: f64, max: f64) -> Self {
        ForgeTensor {
            inner: self.inner.clamp(min as f32, max as f32).expect("clamp failed"),
        }
    }

    // ── Shape ops ───────────────────────────────────────────────────────

    /// Reshape to a new shape (total elements must match).
    pub fn reshape(&self, shape_ptr: *const i64, shape_len: usize) -> Self {
        let shape = shape_from_raw(shape_ptr, shape_len);
        ForgeTensor { inner: self.inner.reshape(shape.as_slice()).expect("reshape failed") }
    }

    /// Transpose dimensions d1 and d2.
    pub fn transpose(&self, d1: i64, d2: i64) -> Self {
        ForgeTensor {
            inner: self.inner.transpose(d1 as usize, d2 as usize).expect("transpose failed"),
        }
    }

    /// Make the tensor contiguous in memory (no-op if already contiguous).
    pub fn contiguous(&self) -> Self {
        ForgeTensor { inner: self.inner.contiguous().expect("contiguous failed") }
    }

    /// Concatenate `count` tensors along `dim`. `tensors` is a pointer to an array of ForgeTensor pointers.
    pub fn cat(tensors: *const *const ForgeTensor, count: usize, dim: i64) -> Self {
        let ptrs = unsafe { std::slice::from_raw_parts(tensors, count) };
        let inner_refs: Vec<&Tensor> = ptrs
            .iter()
            .map(|&p| unsafe { &(*p).inner })
            .collect();
        let result = Tensor::cat(&inner_refs, dim as usize).expect("cat failed");
        ForgeTensor { inner: result }
    }

    // ── Info ────────────────────────────────────────────────────────────

    /// Write the tensor shape into the caller's buffer.
    pub fn shape(&self, out_dims: *mut i64, out_ndim: *mut usize) {
        let dims = self.inner.dims();
        unsafe {
            *out_ndim = dims.len();
            for (i, &d) in dims.iter().enumerate() {
                *out_dims.add(i) = d as i64;
            }
        }
    }

    /// Total number of elements in the tensor.
    pub fn elem_count(&self) -> usize {
        self.inner.elem_count()
    }

    /// Number of dimensions.
    pub fn rank(&self) -> usize {
        self.inner.rank()
    }

    /// Copy tensor data to a caller-owned float32 buffer. Returns 0=ok, -1=error.
    pub fn to_f32_vec(&self, out_data: *mut f32, out_len: *mut usize) -> i32 {
        let flat = match self.inner.flatten_all() {
            Ok(f) => f,
            Err(e) => { set_last_error(e.to_string()); return -1; }
        };
        let vec: Vec<f32> = match flat.to_vec1() {
            Ok(v) => v,
            Err(e) => { set_last_error(e.to_string()); return -1; }
        };
        unsafe {
            *out_len = vec.len();
            std::ptr::copy_nonoverlapping(vec.as_ptr(), out_data, vec.len());
        }
        0
    }

    /// Run backward pass from this tensor as loss. Returns 0=ok, -1=error.
    pub fn backward(&self) -> i32 {
        match self.inner.backward() {
            Ok(_) => 0,
            Err(e) => { set_last_error(e.to_string()); -1 }
        }
    }
}

// ─── ForgeVar ────────────────────────────────────────────────────────────

/// Generates: forge_var_new, forge_var_as_tensor, forge_var_grad, forge_var_free.
#[furst_export]
impl ForgeVar {
    /// Create a trainable variable from float32 data.
    /// `device`: 0=CPU, 1=CUDA:0, 2=CUDA:1, ...
    pub fn new(
        data: *const f32,
        data_len: usize,
        shape_ptr: *const i64,
        shape_len: usize,
        device: i32,
    ) -> Self {
        let slice = unsafe { std::slice::from_raw_parts(data, data_len) };
        let shape = shape_from_raw(shape_ptr, shape_len);
        let dev = device_from_i32(device).expect("invalid device");
        let t = Tensor::from_slice(slice, shape.as_slice(), &dev).expect("var tensor failed");
        let var = Var::from_tensor(&t).expect("var creation failed");
        ForgeVar { inner: var }
    }

    /// Get the tensor value of this Var (for use in forward pass).
    /// Returns a new ForgeTensor handle (caller must free it).
    pub fn as_tensor(&self) -> *mut ForgeTensor {
        Box::into_raw(Box::new(ForgeTensor { inner: self.inner.as_tensor().clone() }))
    }

    /// Compute gradients of `loss` w.r.t. this Var. Returns null if no gradient.
    /// The `loss` tensor should be a scalar (result of sum_all/mean_all).
    pub fn grad(&self, loss: *const ForgeTensor) -> *mut ForgeTensor {
        let loss = unsafe { &(*loss).inner };
        let grad_store = match loss.backward() {
            Ok(gs) => gs,
            Err(e) => {
                set_last_error(e.to_string());
                return std::ptr::null_mut();
            }
        };
        match grad_store.get(self.inner.as_tensor()) {
            Some(grad) => Box::into_raw(Box::new(ForgeTensor { inner: grad.clone() })),
            None => {
                set_last_error("no gradient found for this variable".to_string());
                std::ptr::null_mut()
            }
        }
    }
}
