//! Tensor FFI — exposes candle tensor operations via `#[furst_export] impl`.
//!
//! Uses the opaque handle pattern: `ForgeTensor` and `ForgeVar` are heap-allocated,
//! F# gets typed classes with IDisposable + Finalize (auto-generated by furst-codegen).

use candle_core::{DType, Device, Module, Tensor, Var};
use furst_macro::furst_export;

use crate::error::set_last_error;

/// Opaque handle wrapping a candle `Tensor`.
pub struct ForgeTensor {
    pub(crate) inner: Tensor,
}

/// Opaque handle wrapping a candle `Var` (trainable parameter).
pub struct ForgeVar {
    pub(crate) inner: Var,
}

// ─── Helpers ─────────────────────────────────────────────────────────────

fn device_from_i32(d: i32) -> Result<Device, candle_core::Error> {
    match d {
        0 => Ok(Device::Cpu),
        n => Device::new_cuda(n as usize - 1),
    }
}

fn shape_from_raw(shape_ptr: *const i64, shape_len: usize) -> Vec<usize> {
    let slice = unsafe { std::slice::from_raw_parts(shape_ptr, shape_len) };
    slice.iter().map(|&d| d as usize).collect()
}

// ─── ForgeTensor ─────────────────────────────────────────────────────────

/// Generates: forge_tensor_zeros, forge_tensor_from_f32, forge_tensor_matmul, etc.
/// Auto-generates forge_tensor_free with IDisposable + Finalize in F#.
#[furst_export]
impl ForgeTensor {
    /// Create a tensor of zeros. `device`: 0=CPU, 1=CUDA:0, 2=CUDA:1, ...
    pub fn zeros(shape_ptr: *const i64, shape_len: usize, device: i32) -> Self {
        let shape = shape_from_raw(shape_ptr, shape_len);
        let dev = device_from_i32(device).expect("invalid device");
        let t = Tensor::zeros(shape.as_slice(), DType::F32, &dev).expect("zeros failed");
        ForgeTensor { inner: t }
    }

    /// Create a tensor from a float32 slice.
    pub fn from_f32(
        data: *const f32,
        data_len: usize,
        shape_ptr: *const i64,
        shape_len: usize,
        device: i32,
    ) -> Self {
        let slice = unsafe { std::slice::from_raw_parts(data, data_len) };
        let shape = shape_from_raw(shape_ptr, shape_len);
        let dev = device_from_i32(device).expect("invalid device");
        let t = Tensor::from_slice(slice, shape.as_slice(), &dev).expect("from_f32 failed");
        ForgeTensor { inner: t }
    }

    /// Matrix multiplication. Returns a new tensor.
    pub fn matmul(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.matmul(other).expect("matmul failed") }
    }

    /// Element-wise addition. Returns a new tensor.
    pub fn add(&self, other: *const ForgeTensor) -> Self {
        let other = unsafe { &(*other).inner };
        ForgeTensor { inner: self.inner.add(other).expect("add failed") }
    }

    /// Softmax along a given dimension.
    pub fn softmax(&self, dim: i64) -> Self {
        let dim = if dim < 0 {
            (self.inner.rank() as i64 + dim) as usize
        } else {
            dim as usize
        };
        let result = candle_nn::ops::softmax(&self.inner, dim).expect("softmax failed");
        ForgeTensor { inner: result }
    }

    /// SiLU activation (x * sigmoid(x)).
    pub fn silu(&self) -> Self {
        let result = candle_nn::Activation::Silu.forward(&self.inner).expect("silu failed");
        ForgeTensor { inner: result }
    }

    /// Write the tensor shape into the caller's buffer.
    pub fn shape(&self, out_dims: *mut i64, out_ndim: *mut usize) {
        let dims = self.inner.dims();
        unsafe {
            *out_ndim = dims.len();
            for (i, &d) in dims.iter().enumerate() {
                *out_dims.add(i) = d as i64;
            }
        }
    }

    /// Copy tensor data to a caller-owned float32 buffer. Returns 0=ok, -1=error.
    pub fn to_f32_vec(&self, out_data: *mut f32, out_len: *mut usize) -> i32 {
        let flat = match self.inner.flatten_all() {
            Ok(f) => f,
            Err(e) => { set_last_error(e.to_string()); return -1; }
        };
        let vec: Vec<f32> = match flat.to_vec1() {
            Ok(v) => v,
            Err(e) => { set_last_error(e.to_string()); return -1; }
        };
        unsafe {
            *out_len = vec.len();
            std::ptr::copy_nonoverlapping(vec.as_ptr(), out_data, vec.len());
        }
        0
    }

    /// Run backward pass from this tensor as loss. Returns 0=ok, -1=error.
    pub fn backward(&self) -> i32 {
        match self.inner.backward() {
            Ok(_) => 0,
            Err(e) => { set_last_error(e.to_string()); -1 }
        }
    }
}

// ─── ForgeVar ────────────────────────────────────────────────────────────

/// Generates: forge_var_new, forge_var_as_tensor, forge_var_grad, forge_var_free.
#[furst_export]
impl ForgeVar {
    /// Create a trainable variable from float32 data (always on CPU).
    pub fn new(
        data: *const f32,
        data_len: usize,
        shape_ptr: *const i64,
        shape_len: usize,
    ) -> Self {
        let slice = unsafe { std::slice::from_raw_parts(data, data_len) };
        let shape = shape_from_raw(shape_ptr, shape_len);
        let t = Tensor::from_slice(slice, shape.as_slice(), &Device::Cpu).expect("var tensor failed");
        let var = Var::from_tensor(&t).expect("var creation failed");
        ForgeVar { inner: var }
    }

    /// Get the tensor value of this Var (for use in forward pass).
    /// Returns a new ForgeTensor handle (caller must free it).
    pub fn as_tensor(&self) -> *mut ForgeTensor {
        Box::into_raw(Box::new(ForgeTensor { inner: self.inner.as_tensor().clone() }))
    }

    /// Get the gradient of this Var. Returns null if no gradient.
    pub fn grad(&self) -> *mut ForgeTensor {
        let grad_store = match self.inner.as_tensor().backward() {
            Ok(gs) => gs,
            Err(e) => {
                set_last_error(e.to_string());
                return std::ptr::null_mut();
            }
        };
        match grad_store.get(self.inner.as_tensor()) {
            Some(grad) => Box::into_raw(Box::new(ForgeTensor { inner: grad.clone() })),
            None => {
                set_last_error("no gradient found for this variable".to_string());
                std::ptr::null_mut()
            }
        }
    }
}
